# Day-19(29May)

- Numpy
- Array is a multi-dimensional data structure that stores elements of the same data type in contiguous memory locations.
  - arange()
  - zeros()
  - ones()
  - np.random.rand()
  - np.random.randint()

In [1]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [6]:
li=[1,2,3,4,5]
type(li)

list

In [9]:
arr=np.array(li)
type(arr)

numpy.ndarray

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [17]:
np.arange(40,46)

array([40, 41, 42, 43, 44, 45])

In [19]:
np.arange(20,13) # first arg should be less than second arg

array([], dtype=int32)

In [21]:
np.arange(10,20,3) # only three args

array([10, 13, 16, 19])

In [25]:
np.zeros(10) # parameter tunning - system given default datatype

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros(10,dtype=int) #hyperparameter tunning - user specified

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [28]:
np.zeros((2,5),dtype=int) # 2*5 matrix

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
np.ones(3)

array([1., 1., 1.])

In [31]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
np.two(2,3)#no function

AttributeError: module 'numpy' has no attribute 'two'

In [42]:
np.random.rand(3,3)

array([[0.12916562, 0.20071346, 0.89310293],
       [0.22448959, 0.27781313, 0.63131548],
       [0.61211286, 0.7616846 , 0.78891972]])

In [45]:
np.random.randint(3,6)#2nd arg is n-1

5

In [48]:
np.random.randint(1000,9999,10)#3rg arg is to specify how many

array([9097, 9722, 9595, 3426, 7359, 6964, 8606, 6798, 8431, 1383])

In [53]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Numpy U-Practice
- linspace()
- copy()

In [3]:
import numpy as np
#np.lookfor("arange")

In [3]:
np.arange(3)

array([0, 1, 2])

In [4]:
listt=[1,3,5,9]
id(listt)

2317243266176

In [5]:
id(listt[1])

140717137144312

In [7]:
arr=np.array(listt)
arr

array([1, 3, 5, 9])

In [13]:
print(id(arr[0]),id(arr[1]),id(arr[2]))

2317248153936 2317248153936 2317248153936


In [14]:
arr.shape

(4,)

In [20]:
list1=[1,3,5,7]
list2=[2,4,6,8]
list3=[2,3,5,7]
two_d_arr=np.array([list1,list2,list3])
two_d_arr

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [2, 3, 5, 7]])

In [21]:
two_d_arr.shape

(3, 4)

In [22]:
two_d_arr.reshape(4,3)

array([[1, 3, 5],
       [7, 2, 4],
       [6, 8, 2],
       [3, 5, 7]])

In [24]:
two_d_arr.reshape(12)

array([1, 3, 5, 7, 2, 4, 6, 8, 2, 3, 5, 7])

In [26]:
two_d_arr.reshape(1,12)#reshape within 2d

array([[1, 3, 5, 7, 2, 4, 6, 8, 2, 3, 5, 7]])

In [27]:
# Array Indexing 

In [29]:
od_arr=np.array([1,2,3,4,5])
od_arr

array([1, 2, 3, 4, 5])

In [32]:
od_arr[2] #1d slicing

3

In [33]:
two_d_arr

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [2, 3, 5, 7]])

In [36]:
two_d_arr[1,2]#2-d slicing

6

In [37]:
two_d_arr[1:,]

array([[2, 4, 6, 8],
       [2, 3, 5, 7]])

In [42]:
two_d_arr[1:,2:]

array([[6, 8],
       [5, 7]])

In [43]:
two_d_arr[:2,2:]

array([[5, 7],
       [6, 8]])

In [45]:
# Inbuilts

In [47]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [48]:
arr=np.arange(1,5,3)
arr

array([1, 4])

In [50]:
np.linspace(40,45,10)# linear space b/w the output numbers

array([40.        , 40.55555556, 41.11111111, 41.66666667, 42.22222222,
       42.77777778, 43.33333333, 43.88888889, 44.44444444, 45.        ])

In [53]:
arr1=np.arange(10)
arr2=np.arange(10,20)

In [54]:
arr2=arr1.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr2[3]=30
arr2

array([ 0,  1,  2, 30,  4,  5,  6,  7,  8,  9])

In [57]:
print(arr1,arr2)

[0 1 2 3 4 5 6 7 8 9] [ 0  1  2 30  4  5  6  7  8  9]


In [58]:
arr2[4:]=77
arr2

array([ 0,  1,  2, 30, 77, 77, 77, 77, 77, 77])

In [59]:
var=3
arr2*var

array([  0,   3,   6,  90, 231, 231, 231, 231, 231, 231])

In [62]:
arr2//var

array([ 0,  0,  0, 10, 25, 25, 25, 25, 25, 25], dtype=int32)

In [64]:
arr2[arr2<70]

array([ 0,  1,  2, 30])

In [67]:
np.ones((2,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [68]:
arr2


array([ 0,  1,  2, 30, 77, 77, 77, 77, 77, 77])

In [69]:
arr2[-2]=80
arr2

array([ 0,  1,  2, 30, 77, 77, 77, 77, 80, 77])